# This is a basic workflow to help you get started with Actions

name: rebrand

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  rebrand:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{github.token}}
          workflow: build.yml
          workflow_conclusion: success
          branch: master
          name: rebrander
          repo: Bukkitstom/rebrander
      - run: chmod +x bundle.js
      - run: ./bundle.js --name ${{github.event.repository.name}} --class ${{github.event.repository.name}} --package me.${{github.repository_owner}}.${{github.event.repository.name}} --author ${{github.repository_owner}}
